<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.fc</groupId>
        <artifactId>fc</artifactId>
        <version>3.8.7</version>
    </parent>

    <artifactId>fc-teamschedule</artifactId>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <!--球队日程模块-->
    <!-- 依赖 -->
    <dependencies>
        <dependency>
            <groupId>com.fc</groupId>
            <artifactId>fc-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fc</groupId>
            <artifactId>fc-framework</artifactId>
        </dependency>
    </dependencies>
</project>